default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: my_tasks_development

test:
  <<: *default
  database: my_tasks_test

production:
  <<: *default
  database: my_tasks_production
  username: my_tasks
  password: <%= ENV['MY_TASKS_DATABASE_PASSWORD'] %>
